# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a48cdf3454452a0c54821a21104f6b6379a95abb8adfe7c3ad02665239b64402290cd14215d1e1551d9bdf1504cfdf45cb52ede9f6da930a5d5a930d69deea32

test:
  secret_key_base: 8c91514b3d9e786758c641d38ab556230c53154dd278566f78635f248f21ef97160c2f22f826724b2fe887d7dc01e044b38c75add7c6293afe70d21892f5ddeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
